version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.front
    restart: always
    env_file:
      - .env
    ports:
      -  "${FRONT_PORT}:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.back
    restart: always
    env_file:
      - .env
    ports:
      -  "${BACK_PORT}:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
